name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Enable additional repositories
        run: |
          dnf install -y dnf-plugin-config-manager

          # CRB is required for meson
          dnf config-manager -y --set-enabled crb

          # EPEL is required for codespell
          dnf install -y epel-release

      - name: Install dependencies
        run: |
          dnf install \
                  clang-tools-extra \
                  gcc \
                  git \
                  meson \
                  systemd-devel \
                  codespell \
              -y

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check SPDX headers
        run: |
          ./build-scripts/spdx-header-check.sh

      - name: Running source code format check
        run: |
          make check-fmt

      - name: Running static analysis
        run: |
          make lint

      - name: Running codespell checker
        run: |
          make check-codespell

      - name: Running markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v9

  rpmbuild:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    env:
      ARTIFACTS_DIR: exported-artifacts

    steps:
      - name: Enable additional repositories
        run: |
          dnf install -y dnf-plugin-config-manager

          # CRB is required for meson
          dnf config-manager -y --set-enabled crb

      - name: Install dependencies
        run: |
          dnf install \
                  createrepo_c \
                  dnf-utils \
                  gcc \
                  git \
                  gzip \
                  meson \
                  rpm-build \
                  sed \
                  systemd-devel \
                  tar \
                  golang-github-cpuguy83-md2man \
              -y

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Build hirte.spec
        run: |
          git config --global --add safe.directory $(pwd)
          meson setup builddir

      - name: Perform build
        run: |
          ./build-scripts/build-rpm.sh $ARTIFACTS_DIR builddir/rpm/hirte.spec

      - name: Create DNF repository
        run: |
          createrepo_c $ARTIFACTS_DIR

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rpm-artifacts
          path: ${{ env.ARTIFACTS_DIR}}

  e2e:
    needs: rpmbuild
    uses: ./.github/workflows/e2e.yml

