name: Integration Testing  

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: cs9 x86_64 e2e 
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y install podman 

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build hirte tests containers
        run: |
          podman run --rm --name hirte-builder \
          -v  ${PWD}:/hirte:Z -it quay.io/yarboa/hirte-builder:1.0.0 \
          /bin/bash -c "rm -rf builddir; meson setup builddir; \
          meson install -C builddir --destdir bin"
          podman build -f tests/Containerfile -t hirte-image .

      - name: run hirte containers
        run: |
          podman run -d --net podman --rm -p 2020:2020 --name hirte-mgr \
          $(podman images *hirte-image --format {{.ID}})
          podman run -d --net podman --rm --name hirte-agent-foo \
          $(podman images *hirte-image --format {{.ID}})
          podman run -d --net podman --rm --name hirte-agent-bar \
          $(podman images *hirte-image --format {{.ID}})
          PODMAN_NET=$(hostname -I | awk '{print $1}')
          echo "PODMAN_NET=$PODMAN_NET" >> $GITHUB_ENV

      - name: run hirte orchestrator
        run: |
          podman exec -t  hirte-mgr \
          su - test-user -c  "(/usr/local/bin/hirte -c /hirte/example-hirte.ini > mgr.log 2>&1 &)"

      - name: run hirte agent-bar
        run: |
          # Change node name in config file
          podman exec -it hirte-agent-bar \
          sed -i "s/\(Name=\)\(.*\)/\1bar/" /hirte/example-hirte-agent.ini
          # Change manager address in config file
          podman exec -it hirte-agent-bar \
          sed -i "s/\(Host=\)\(.*\)/\1${{ env.PODMAN_NET }}/" /hirte/example-hirte-agent.ini
          podman exec -t hirte-agent-bar \
          su - test-user -c "(/usr/local/bin/hirte-agent -c \
          /hirte/example-hirte-agent.ini > bar.log 2>&1 &)"
          podman exec -it hirte-agent-bar /usr/bin/pkill --signal TERM hirte-agent
          podman exec -w /home/test-user -u test-user -it hirte-agent-bar \
          grep "Registered.* as 'bar'" bar.log

      - name: run hirte agent-foo
        run: |
          # Change node name in config file
          podman exec -it hirte-agent-foo \
          sed -i "s/\(Name=\)\(.*\)/\1foo/" /hirte/example-hirte-agent.ini
          # Change manager address in config file
          podman exec -it hirte-agent-foo \
          sed -i "s/\(Host=\)\(.*\)/\1${{ env.PODMAN_NET }}/" /hirte/example-hirte-agent.ini
          podman exec -t hirte-agent-foo \
          su - test-user -c  "(/usr/local/bin/hirte-agent -c \
          /hirte/example-hirte-agent.ini > foo.log 2>&1 &)"
          podman exec -it hirte-agent-foo /usr/bin/pkill --signal TERM hirte-agent
          podman exec -w /home/test-user -u test-user -it hirte-agent-foo \
          grep "Registered.* as 'foo'" foo.log

