name: Container Images

on:
  workflow_dispatch:
    inputs:
      image:
        description: Name of the image to build and push to quay.io
        required: true
        type: choice
        options:
        - build-base
        - integration-test-base

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build manifest
        run: |
          ./build-scripts/build-push-containers.sh ${{ inputs.image }}

      - name: Push manifest o quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ inputs.image }}
          registry: quay.io/bluechi
          username: bluechi+bluechi_bot
          password: ${{ secrets.QUAY_BOT_API_TOKEN }}
